### ISSUE TITLE
[Feature Request] badges for heuristic rating

### ISSUE THREAD

**Issue by qz-cqy** [renbaoshuo/atcoder-rating#1]
Hi! Thank you for this useful tool :)

How about offering the possibility to generate badges which show the heuristic rating?

**Comment by renbaoshuo** [comment]
Thanks for your idea! I've added this feature in https://github.com/renbaoshuo/atcoder-rating/commit/b36e2a686f71b21df9968bc4bd184ee3a4d32f01 .

Here's an example:

![](https://atrating.baoshuo.dev/api/rating?username=rui_er&type=heuristic)
